kos = read.csv("dailykos.csv")
distance = dist(kos, method="euclidean")
kClust =  hclust(distance, metho = "ward.D")
plot(kClust)
kosClusters <- cutree(kClust, k = 7)
cluster1 <- subset(kos, kosClusters == 1)
cluster2 <- subset(kos, kosClusters == 2)
cluster3 <- subset(kos, kosClusters == 3)
cluster4 <- subset(kos, kosClusters == 4)
cluster5 <- subset(kos, kosClusters == 5)
cluster6 <- subset(kos, kosClusters == 6)
cluster7 <- subset(kos, kosClusters == 7)

set.seed(1000)
km = kmeans(as.vector(as.matrix(kos)), centers = 7)
str(km)
KMclusters = km$cluster

table(KMclusters)
kc1 = subset(kos, km$cluster == 1)
kc2 = subset(kos, km$cluster == 2)
kc3 = subset(kos, km$cluster == 3)
kc4 = subset(kos, km$cluster == 4)
kc5 = subset(kos, km$cluster == 5)
kc6 = subset(kos, km$cluster == 6)
kc7 = subset(kos, km$cluster == 7)
# KMcluster2 <- subset(kos, KMclusters == 2)
# KMcluster3 <- subset(kos, KMclusters == 3)
# KMcluster4 <- subset(kos, KMclusters == 4)
# KMcluster5 <- subset(kos, KMclusters == 5)
# KMcluster6 <- subset(kos, KMclusters == 6)
# KMcluster7 <- subset(kos, KMclusters == 7)

